
@subdominio = examen-ecv-2
##########
GET http://{{subdominio}}.onrender.com/
###
GET http://{{subdominio}}.onrender.com/idat/codigo
###
GET http://{{subdominio}}.onrender.com/idat/nombre-completo


###
GET http://{{subdominio}}.onrender.com/api/curso/all


###
POST http://{{subdominio}}.onrender.com/api/curso/nuevo HTTP/1.1
Content-Type: application/x-www-form-urlencoded

nom=PRUEBA
&creditos=20

###

PUT http://{{subdominio}}.onrender.com/api/curso/editar HTTP/1.1
Content-Type: application/x-www-form-urlencoded

id=102
&nom=Comunicacion
&creditos=400

###

DELETE http://{{subdominio}}.onrender.com/api/curso/eliminar HTTP/1.1
Content-Type: application/x-www-form-urlencoded

id=2

###
GET http://{{subdominio}}.onrender.com/api/curso/get/1 HTTP/1.1
###


